name: Export Bitrix24 Data

on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * *'  # 08:30 по UTC, что соответствует 10:30 по времени Словении (GMT+2)

jobs:
  export-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run export script
      run: python export_bitrix24_data.py

    - name: Check if CSV file exists
      run: ls -l deals_data.csv

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add deals_data.csv
        git commit -m 'Updated deal data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
